/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ergasiaproodou;

import ergasiaproodou.guis.absencehistory.AddAbsence;
import ergasiaproodou.guis.absencehistory.ChangeAbsence;
import ergasiaproodou.guis.absencehistory.DeleteAbsence;
import ergasiaproodou.guis.absencehistory.ViewAbsensce;
import ergasiaproodou.guis.emails.AddEmail;
import ergasiaproodou.guis.emails.ChangeEmail;
import ergasiaproodou.guis.emails.DeleteEmail;
import ergasiaproodou.guis.emails.ViewEmails;
import ergasiaproodou.guis.employee.AddEmployee;
import ergasiaproodou.guis.employee.ChangeEmployee;
import ergasiaproodou.guis.employee.DeleteEmployee;
import ergasiaproodou.guis.employee.ViewEmployees;
import ergasiaproodou.guis.healthhistory.AddHealthHistory;
import ergasiaproodou.guis.healthhistory.ChangeHealthHistory;
import ergasiaproodou.guis.healthhistory.DeleteHealthHistory;
import ergasiaproodou.guis.healthhistory.ViewHealthHistory;
import ergasiaproodou.guis.salaryhistory.AddSalaryHistory;
import ergasiaproodou.guis.salaryhistory.ChangeSalaryHistory;
import ergasiaproodou.guis.salaryhistory.DeleteSalaryHistory;
import ergasiaproodou.guis.salaryhistory.ViewSalaryHistory;
import ergasiaproodou.guis.telephones.AddTelephone;
import ergasiaproodou.guis.telephones.ChangeTelephone;
import ergasiaproodou.guis.telephones.DeleteTelephone;
import ergasiaproodou.guis.telephones.ViewTelephones;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author PST2
 */
public class Tree extends javax.swing.JFrame {

    /**
     * Creates new form Tree
     */
    public Tree() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jButton1 = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("EMPLOYEES");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("ADD EMPLOYEE");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("CHANGE EMPLOYEE");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("DELETE EMPLOYEE");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("VIEW EMPLOYEES");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("ABSENCE HISTORY");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("ADD ABSENCE");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("CHANGE ABSENCE");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("DELETE ABSENCE");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("VIEW ABSENCE");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("EMAILS");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("ADD EMAIL");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("CHANGE EMAIL");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("DELETE EMAIL");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("VIEW EMAIL");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("TELEPHONES");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("ADD TELEPHONE");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("CHANGE TELEPHONE");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("DELETE TELEPHONE");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("VIEW TELEPHONES");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("HEALTH HISTORY");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("ADD HEALTH HISTORY");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("CHANGE HEALTH HISTORY");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("DELETE HEALTH HISTORY");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("VIEW HEALTH HISTORY");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("SALARY HISTORY");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("ADD SALARY HISTORY");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("CHANGE SALARY HISTORY");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("DELETE SALARY HISTORY");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("VIEW SALARY HISTORY");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTree1);

        jButton1.setText("GO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         navigate();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tree().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables

    private void navigate(){
        
             
       
       String selected = String.valueOf(jTree1.getLastSelectedPathComponent());
       
           if (selected.equalsIgnoreCase("ADD EMPLOYEE")){
            AddEmployee ae = new AddEmployee();
            ae.setVisible(true);
            
       } else if  (selected.equalsIgnoreCase("CHANGE EMPLOYEE")){
             ChangeEmployee ce = new ChangeEmployee();
            ce.setVisible(true);
       } else if  (selected.equalsIgnoreCase("DELETE EMPLOYEE")){
             DeleteEmployee ce = new DeleteEmployee();
            ce.setVisible(true);
     } else if  (selected.equalsIgnoreCase("VIEW EMPLOYEES")){
             ViewEmployees ve = new ViewEmployees();
            ve.setVisible(true);
  /*
            
            END OF EMPLOYEES
            
            */
      } else if  (selected.equalsIgnoreCase("ADD ABSENCE")){
             AddAbsence aa = new AddAbsence();
            aa.setVisible(true);
    
    } else if  (selected.equalsIgnoreCase("CHANGE ABSENCE")){
             ChangeAbsence ca = new ChangeAbsence();
            ca.setVisible(true);
    
       } else if  (selected.equalsIgnoreCase("DELETE ABSENCE")){
             DeleteAbsence da = new DeleteAbsence();
            da.setVisible(true);
       } else if  (selected.equalsIgnoreCase("VIEW ABSENCE")){
             ViewAbsensce da = new ViewAbsensce();
            da.setVisible(true);
            
                  /*
            
            END OF ABSENCE
            
            */
            
            
       } else if  (selected.equalsIgnoreCase("ADD EMAIL")){
             AddEmail ae = new AddEmail();
            ae.setVisible(true);
    
       } else if  (selected.equalsIgnoreCase("ADD EMAIL")){
             AddEmail ae = new AddEmail();
            ae.setVisible(true);
            
         
            
    } else if  (selected.equalsIgnoreCase("CHANGE EMAIL")){
             ChangeEmail ce = new ChangeEmail();
            ce.setVisible(true);
    
       } else if  (selected.equalsIgnoreCase("DELETE EMAIL")){
             DeleteEmail da = new DeleteEmail();
            da.setVisible(true);
    } else if  (selected.equalsIgnoreCase("VIEW EMAIL")){
             ViewEmails ve = new ViewEmails();
            ve.setVisible(true);
 
     
                  /*
            
            END OF EMAIL
            
            */
    
       } else if  (selected.equalsIgnoreCase("ADD TELEPHONE")){
             AddTelephone at = new AddTelephone();
            at.setVisible(true);
    
    } else if  (selected.equalsIgnoreCase("CHANGE TELEPHONE")){
             ChangeTelephone ct = new ChangeTelephone();
            ct.setVisible(true);
    
       } else if  (selected.equalsIgnoreCase("DELETE TELEPHONE")){
             DeleteTelephone dt = new DeleteTelephone();
            dt.setVisible(true);
    
    }
              else if  (selected.equalsIgnoreCase("VIEW TELEPHONES")){
             ViewTelephones vt = new ViewTelephones();
            vt.setVisible(true);
    
 
           
            
                  /*
            
            END OF TELEPHONES
            
            */
           }
              else if  (selected.equalsIgnoreCase("ADD HEALTH HISTORY")){
             AddHealthHistory ahh = new AddHealthHistory();
            ahh.setVisible(true);
    
      }
              else if  (selected.equalsIgnoreCase("CHANGE HEALTH HISTORY")){
             ChangeHealthHistory chh = new ChangeHealthHistory();
            chh.setVisible(true);
    
    } 
               else if  (selected.equalsIgnoreCase("DELETE HEALTH HISTORY")){
             DeleteHealthHistory dhh = new DeleteHealthHistory();
            dhh.setVisible(true);
    
    } 
           
                        else if  (selected.equalsIgnoreCase("VIEW HEALTH HISTORY")){
             ViewHealthHistory dhh = new ViewHealthHistory();
            dhh.setVisible(true);
    
    } 
           
            
                  /*
            
            END OF HEALTH HISTORY
            
            */
 
        else if  (selected.equalsIgnoreCase("ADD SALARY HISTORY")){
             AddSalaryHistory ash = new AddSalaryHistory();
            ash.setVisible(true);
    
        }
           
              else if  (selected.equalsIgnoreCase("CHANGE SALARY HISTORY")){
             ChangeSalaryHistory csh = new ChangeSalaryHistory();
            csh.setVisible(true);
    
        }     else if  (selected.equalsIgnoreCase("DELETE SALARY HISTORY")){
            DeleteSalaryHistory dsh = new DeleteSalaryHistory();
            dsh.setVisible(true);
    
        }
                else if  (selected.equalsIgnoreCase("VIEW SALARY HISTORY")){
            ViewSalaryHistory vsh = new ViewSalaryHistory();
            vsh.setVisible(true);
    
        } else{
                    JOptionPane.showMessageDialog(null, "PLEASE SELECT AN OPTION");
                }
    }
    
}